### ISSUE TITLE
Feature Request: Generalise ci.test to allow a vector of values

### ISSUE THREAD

**Issue by sjvrensburg** [leifeld/texreg#129]
Is it possible to modify the `ci.test` argument to accept a vector of values?

### Description Of The Problem
Currently, the `ci.test` argument allows only for a scalar value. There are, however, situations where different reference values for different coefficients are appropriate. Allowing only a single reference value is especially problematic when using stars to highlight significant coefficients.

### Motivating Example
For example, I am working with models of log-volatility based on a skewed distribution. The skewing parameter must exceed zero. The distribution is symmetric if the skewing parameter is one. Therefore, the appropriate reference value for the CI is one. For other parameters, zero is the appropriate reference value. Finally, there are also coefficients / parameters for which reporting "significance" doesn't make sense. E.g. what should one test omega, the long-run log-volatility, against?

### Minimal Working Example
Below is a minimal working example, illustrating the issue.
```R
coef_names <- c("omega", # long-run log-volatility
                "alpha", # GAS/score coefficient
                "beta",  # persistence
                "skew",  # skewing parameter > 0
                "nu")    # tail-weight parameter
coef_est <- c(1, 0.05, 0.95, 0.8, 5)
se <- c(0.5, 0.01, 0.001, 0.3, 1.5)
z_stat <- (coef_est - c(0, 0, 0, 1, 0))
p_val <- 2*pnorm(abs(z_stat), lower.tail = FALSE)
ci_l <- coef_est - 1.96*se
ci_u <- coef_est + 1.96*se

texreg_obj <- texreg::createTexreg(coef.names = coef_names,
                                   coef = coef_est, se = se,
                                   pvalues = p_val,
                                   ci.low = ci_l, ci.up = ci_u)

# Not sensible for the skewing parameter.
texreg::screenreg(texreg_obj, ci.test = 0)
# Only sensible for the skewing parameter.
texreg::screenreg(texreg_obj, ci.test = 1)
# Appropriate for omega and maybe nu
texreg::screenreg(texreg_obj, ci.test = NULL)
```
Ideally, I would like to be able to supply a vector of values to `ci.test`:
```R
ci_tests <- c(NULL, 0, 0, 1, NULL)
texreg::screenreg(texreg_obj, ci.test = ci_tests)
```
This should produce a table that indicates (by stars) that only alpha and beta are significant at the 5% level. Unfortunately, using texreg version 1.36.23, this results in three identical tables where only the significance note differs.

### Session Information
```R
> sessionInfo()
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.2 LTS

Matrix products: default
BLAS: /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so

locale:
 [1] LC_CTYPE=en_ZA.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_ZA.UTF-8        LC_COLLATE=en_ZA.UTF-8    
 [5] LC_MONETARY=en_ZA.UTF-8    LC_MESSAGES=en_ZA.UTF-8   
 [7] LC_PAPER=en_ZA.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_ZA.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.4 texreg_1.36.23
```

I hope the above makes sense.

**Comment by leifeld** [comment]
Thanks for this suggestion and sorry for the long delay in getting to this.

I think it makes sense to extend the `ci.test` argument to accept numeric vectors. However, I think it is more important to be able to set different `ci.test` null hypothesis values for different models, rather than different coefficients.

The `ci.force` argument already accepts vectors. If multiple logical values are provided, this permits forcing some models to have confidence intervals while others can have standard errors. Similarly, it should be possible have different null hypothesis values in `ci.test` because some models may have coefficients on the log-odds scale while others have them on the odds-ratio scale. I have therefore extended the `ci.test` argument to allow numeric vectors for different models, rather than different coefficients of the same model, in commit 7a889800872e1cf0bc470be36a019282e8fde6e7.

I wouldn't know how best to extend this further to also permit multiple values per model. Perhaps vectors for coefficients nested in a list for different models? But that's not very intuitive if a user only wants a vector (or list in that case) for the different models. Perhaps a matrix with coefficient-specific values for different models? But that can get quite tricky with arguments like `single.row = TRUE`, empty cells when a model does not have a specific model term etc.

So for now, I have decided to leave it at the changes implemented in 7a889800872e1cf0bc470be36a019282e8fde6e7. I hope that's understandable.
