### ISSUE TITLE
Transposing regression outputs

### ISSUE THREAD

**Issue by shoonlee** [leifeld/texreg#151]
Hi! Thanks for the great package!

I'm trying to create a table that summarizes 20+ regression results by presenting an estimate and standard error from the same term. Importantly, the right hand side of these regressions are identical, but dependent variables and the datasets are different. Thus I want the table to report a single coefficient of interest for a combination of dependent variables (rows) and sample (columns). I've tried doing this by using ```createTexreg``` function, but placing dependent variables in a row doesn't seem to work.

To make things more concrete, I attached a sample table from a paper. Column (1)-(5) are based on different samples. Household income, public assistance, and college graduates are three different dependent variables. Please feel free to let me know if further clarification is needed. Also, if this can be achieved in other ways, that information would be extremely helpful. 

Thank you!
![samp](https://user-images.githubusercontent.com/52023556/82724309-12487f00-9d10-11ea-873f-6422f340ac6b.png)

**Comment by leifeld** [comment]
Thanks for the question. I think that's outside of the scope of `texreg`, unfortunately. I've been thinking about how to achieve this, but merely transposing the data wouldn't do the trick: While the dependent variables from the columns would be moved to the rows, the columns would then show the coefficients instead of samples. Adding in different samples is more like adding different models, I suppose. I would suggest extracting the relevant coefficients manually from the respective models, arranging them in a character matrix, and using a general-purpose table generation package or tool to display or export them in the format you wish, such as `huxtable`, `kable`, or `xtable`. Perhaps the `matrixreg` function in the `texreg` package can help you extract the coefficients in the format you need, and you can then re-arrange them in a new matrix and use those tools. Hope this is at least somewhat helpful...
