### ISSUE TITLE
rmarkdown word_document does not work

### ISSUE THREAD

**Issue by albertostefanelli** [leifeld/texreg#152]
As per title, 

Knitting a texreg table in rmarkdown in a word .docx document does not work.
Please update the CRAN documentation. 
Attached a reproducible example. 
Word version: Mac OS 16.16.22 (200509)

[Archive.zip](https://github.com/leifeld/texreg/files/4746417/Archive.zip)

**Comment by leifeld** [comment]
I cannot see any call to either the `wordreg` or the `knitreg` function in your example. One of these two is required to compile a document directly into an MS Word document. The use of `htmlreg` works only by opening the resulting HTML document in MS Word and copying the contents, but HTML documents are not the native format of MS Word.

**Comment by albertostefanelli** [comment]
Hi leifeld, thanks for the super quick answer.

Indeed, calling `kintreg` produce the desired result. Thanks! 

However, I still suggest changing the vignette on CRAN. The section 5.6. "htmlreg(), Microsoft Word, knitr, and Markdown" does not mention neither the `kintreg` nor `wordreg` functions

**Comment by leifeld** [comment]
Great!

The vignette is a copy of my 2013 article in the Journal of Statistical Software. The first paragraph mentions that the vignette has not been, and will not be, updated and that the package now has a number of additional features. At the time, it was not possible to knit into Word documents directly. If I have enough time (though that's my most valuable resource), I may add a second vignette with updates since 2013 at some point.
