### ISSUE TITLE
report t values instead of standard errors beneath regression coefficients 

### ISSUE THREAD

**Issue by waynelapierre** [leifeld/texreg#163]
How can I make texreg's generated latex regression results report t values instead of standard errors beneath regression coefficients?

**Comment by richardcherron** [comment]
To replace standard errors with t-statistics, use the `override.se` and `override.pvalues` arguments. The package author has a [StackOverflow](https://stackoverflow.com/questions/27078936/how-to-display-t-value-in-texreg) post that should help.

**Comment by waynelapierre** [comment]
That is far from a solution.

**Comment by richardcherron** [comment]
I think the package author's solution is reasonable. You could code your own solution and make a pull request. It looks like the package author has processed 60 pull requests.

**Comment by waynelapierre** [comment]
The stargazer R package can report t values beneath regression coefficients. Maybe texreg can borrow some ideas from stargazer.

**Comment by leifeld** [comment]
Different packages do things in different ways. If stargazer is better tailored to your needs, I would recommend using it instead of texreg. For my own usage, texreg works just as I want it to. But if you have suggestions via a pull request, I'm happy to consider them, as is customary in open source development.
