### ISSUE TITLE
custom.note option creates issue with star symbol with RMarkdown

### ISSUE THREAD

**Issue by morihe** [leifeld/texreg#172]
I spotted a minor issue when using `htmlreg()` in an Rmd file when using the chunk option `results = "asis"` to include the html output directly in the knitted html document. 

First, the help file suggests using `"\*"` for the star.symbol in combination with Rmd which I think should be `"\\*"`. Otherwise I get the following error message: Error: '\*' is an unrecognized escape in character string starting ""\*" Execution halted.

Using `htmlreg(mod, star.symbol = "\\*")` works perfectly well until I add the option `custom.note = "%stars. My note."`. Is there any way to use both options to preserve the star symbol in RMarkdown *and* have a custom note?

The minimal example (omitting the code chunk borders) would look like
```
---
output: html_document
---

{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(texreg)


{r}
mod <- lm(mpg ~ qsec, data = mtcars)


{r, results = "asis"}
# Error: '\*' is an unrecognized escape in character string starting ""\*" Execution halted
# htmlreg(mod, star.symbol = "\*")

# works fine
htmlreg(mod, star.symbol = "\\*")

# stars messed up
htmlreg(mod, star.symbol = "\\*", custom.note = "%stars. My note.")
```

**Comment by leifeld** [comment]
The problem arises because `\\*` is not a proper HTML character. It kind of works in Markdown, but it's probably better to use a proper HTML symbol, which should also work in Markdown, such as `&#42;`, which is rendered as &#42;. The internal replacement with regular expressions tends to be tricky and kill of some of the backslashes of escape characters. It would have worked with `\\\\*`, but that's of course not very intuitive. To fix this, I have now changed the default argument of `htmlreg` to be `star.symbol = "&#42;"`, which means you should no longer have a problem with backslashes getting killed in custom notes.

**Comment by morihe** [comment]
Thank you so much!
