### ISSUE TITLE
if (..) length greater one 

### ISSUE THREAD

**Issue by nschwitter** [leifeld/texreg#206]
Hello,

I believe the `texreg` package has not sufficiently guarded against R-4.2's change to error when if (..) is of length greater than one. I am currently re-running some code which has worked seamlessly the last time I used it (August 2022). I try to convert negative binomial models I obtained using `glmmTMB`. When trying to screenreg them, I get the following warning: `Error in include.variance == TRUE && !is.na(s$ngrps) : 'length = 2' in coercion to 'logical(1)'`.

I think the issue is the `&&` and the changes made within R (other packages seem to have had the same problem, see e.g. here [R Warning 'length(x) = 2 > 1' in coercion to 'logical(1)'](https://stackoverflow.com/questions/72848442/r-warning-lengthx-2-1-in-coercion-to-logical1).

MWE:
<code>library(glmmTMB)
library(texreg)
data("mtcars")
cars <- glmmTMB(gear ~ mpg, data=mtcars)
summary(cars)
screenreg(cars)</code>

**Comment by leifeld** [comment]
This was already fixed in b06d80a86bfcb45d92ba8a10b1dc3447836d9454 in March this year, but it hasn't made its way to CRAN yet. I will submit a new version to CRAN today. That said, your example reveals another problem: When the variance component has zero rows because there are only fixed effects, using `include.groups = TRUE` with `extract.glmmTMB` still causes an error. I will fix this as well and include a unit test.

**Comment by nschwitter** [comment]
Thank you! While I made sure to use the most recent version on CRAN, I forgot to check the commit history, sorry - but I am glad the example revealed another error.
