### ISSUE TITLE
write to xlsx directly

### ISSUE THREAD

**Issue by alanpaulkwan** [leifeld/texreg#23]
This would likely be a lot of work, but I'm wondering if its possible to use a package like xlsx or reporteR to print a texreg directly to a file. I can experiment with it. If anyone has an easy idea for how to implement, that would be awesome.

**Comment by leifeld** [comment]
Go for it! You could call it `excelreg()`...

It would also be great to have a dedicated function for creating Markdown tables. Right now, ``htmlreg`` can be used to create HTML tables, and HTML can be embedded in Markdown. But for some reason, this does not work in all implementations of Markdown, such as RStudio. In those cases, a real Markdown table would be preferable... If anyone wants to do it, feel free!

**Comment by MichaelChirico** [comment]
It guess it could be as simple as providing a nice wrapper to `htmlreg` to embed the output in `xml`-friendly format? I don't know enough about basic structure of `.xls` files to go beyond that

**Comment by leifeld** [comment]
HTML tables can be read by MS Office right now. There are two difficulties with this I am aware of: 1. they have to be opened and then re-saved as a proper xlsx or docx file. 2. Depending on the locale, some coefficients may end up with commas as decimal points while others don't (depending on whether there are significance stars). In all other respects, even the whole formatting is preserved.

Creating a function that writes to xlsx directly may be hard to do. As Mike points out, xlsx is an XML format, so it shouldn't be too hard in principle. However, the documentation of MS Office's file formats is not very good (see [here](http://stackoverflow.com/questions/4886027/looking-for-a-clear-description-of-excels-xlsx-xml-format) for a StackOverflow question that points to some documentation).

Perhaps a good solution for those who don't want to import HTML into Excel would be a ``dataframereg`` or ``dfreg`` function, which converts the model output into a data frame? That way, users could employ functions such as ``write.csv`` to write CSV files, which can also be imported in Excel. It shouldn't be hard to do. Of course, all the formatting would be lost... At the same users could then employ the ``kable`` function from ``knitr`` to write Markdown tables. The only issue is that there is no proper formatting with tables like that, i.e., no horizontal line between coefficient and GOF block and the numbers would have to be printed as text because there are significance stars...

**Comment by alanpaulkwan** [comment]
I will casually look into this over the next month (the worst timing for
me, last year of grad school). I believe that getting the positioning of
text is not hard using the xlsx package , which can be a function-level
require. Not sure about formatting.

**Comment by MichaelChirico** [comment]
untested, but might be able to use Rio capabilities to import output as
html table then export as xlsx:

https://cran.r-project.org/web/packages/rio/vignettes/rio.html

**Comment by leifeld** [comment]
Thanks. I like your ideas about xlsx and Rio.

In addition to that, here is another comment I received by e-mail from Shahram Amini on 11 November 2016, which supports my idea of having something like a ``dataframereg`` function. I am trying to group comments on the same topic together by issue thread, so here it is:

> `texreg` package puts the estimates of multiple regressions in a nicely formatted table along with R-squared, number of observations, etc at the bottom of the table. Is there anyway I could have `texreg` give me only a "matrix"  of the estimates (with asterisks) and the standard errors or t values inside parentheses right below the estimates along with two extra rows at the bottom for number of observations and R-squared? Something like this:
> 
> ==================
> 
> 1.203***  0.015*   4.899**
> 
> (0.023)    (0.675)   (2.345)
> 
> 5.278**  1.445**   0.0193***
> 
> (2.224)    (1.567)  (0.001)
> 
> 344         789          299
> 
> 0.35       0.87          0.12
> 
> ==================
> 
> If i can get an output like above then I can customize it based on my needs. Thank you in advance for your help.

**Comment by vincentarelbundock** [comment]
For the record, https://github.com/leifeld/texreg/pull/44 allows you to save to Word documents or CSV spreadhseets.
