### ISSUE TITLE
Support for siunitx

### ISSUE THREAD

**Issue by eivindhammers** [leifeld/texreg#65]
`dcolumn` is mature for replacement by `siunitx`. Any plans of at least adding it? In my fork I've simply replaced https://github.com/leifeld/texreg/blob/4129fee0c9f69947e2026f04c0404d5683f10517/R/texreg.R#L401-L402

with 

```
coldef <- paste0(coldef, "S[table-format=", dl, separator, dr, "]", margin.arg, " ")
```

and it works in my use cases.

I also needed to replace `star.prefix = "^{", ` with `star.prefix  = "\\sym{",` and add 

```
 # \sym definition
  string <- paste0(string, "\\def\\sym#1{\\ifmmode^{#1}\\else\\(^{#1}\\)\\fi}")
```

right after https://github.com/leifeld/texreg/blob/4129fee0c9f69947e2026f04c0404d5683f10517/R/texreg.R#L408

**Comment by leifeld** [comment]
Sorry it took me so long to get to this. I have now implemented `siunitx` support in the `texreg` function. It was a bit more complicated because I also had to rule out conflicts with the `dcolumn` and `bold` arguments, add a `\usepackage{siunitx}` line at the top, fix some issues with the calculation of the width left and right of the separator, and figure out the right configuration also for `single.row = TRUE` and other cases. I did not use the `sym` definition suggested in the original post, but had to include `\sisetup{parse-numbers = false, table-text-alignment=centre}` before the `tabular` environment. This prevents the cell contents from being interpreted as numbers. It's necessary as some cells may have parentheses, significance stars etc., which cannot be interpreted as part of a number. I hope the solution works well for everyone.

Here is an example:

``` r
library("texreg")
data("iris")
model1 <- lm(Sepal.Width ~ Petal.Width, data = iris)
texreg(list(model1, model1),
       single.row = TRUE,
       siunitx = TRUE,
       custom.gof.rows = list(abc = c("abcdefg hijklmn", "abc")))
```
This yields:
```
\usepackage{siunitx}

\begin{table}
\begin{center}
\sisetup{parse-numbers = false, table-text-alignment=centre}
\begin{tabular}{l S[table-format=3.11] S[table-format=3.11]}
\hline
 & {Model 1} & {Model 2} \\
\hline
(Intercept) & 3.31 \; (0.06)^{***}  & 3.31 \; (0.06)^{***}  \\
Petal.Width & -0.21 \; (0.04)^{***} & -0.21 \; (0.04)^{***} \\
\hline
abc         & {abcdefg hijklmn}     & {abc}                 \\
R$^2$       & 0.13                  & 0.13                  \\
Adj.\ R$^2$ & 0.13                  & 0.13                  \\
Num.\ obs.  & 150                   & 150                   \\
\hline
\multicolumn{3}{l}{\scriptsize{$^{***}p<0.001$; $^{**}p<0.01$; $^{*}p<0.05$}}
\end{tabular}
\caption{Statistical models}
\label{table:coefficients}
\end{center}
\end{table}
```
