### ISSUE TITLE
omit.coef with custom.coef.name documented incorrectly

### ISSUE THREAD

**Issue by rmcd1024** [leifeld/texreg#71]
The documentation for 1.36.23, (texreg/omit.coef) says: "The ‘omit.coef' argument is processed after the custom.coef.names’ argument, so the regular expression should refer to the custom coefficient names."

This is incorrect as demonstrated by the following, where the omission is based on the original variable name rather than the custom name:

```
library(texreg)
y <- 1:20 + rnorm(20)
x1 <- rnorm(20)
x2 <- rnorm(20)
reg <- list()

reg[[1]] <- lm(y ~ x1)
reg[[2]] <- lm(y ~ x2)
reg[[3]] <- lm(y ~ x1 + x2)

texreg(reg) # three coefficients
texreg(reg, custom.coef.names=c('a', 'b3', 'b5'),
       omit.coef='2')  ## this omits "b5"
texreg(reg,  custom.coef.names=c('a', 'b3', 'b5'),
       omit.coef='b3')  ## output is unchanged 
```

**Comment by rmcd1024** [comment]
So I finally looked at the code. Based on use (at least my use) I suggest leaving the behavior as documented, i.e. to first rename and then to process omits.  

From R/texreg.R, `omitcoef` is processed before `customnames`
```
  if (!is.null(custom.coef.map)) {
    m <- custommap(m, custom.coef.map)
  } else {
    m <- omitcoef(m, omit.coef)  #remove coefficient rows matching regex
    m <- customnames(m, custom.coef.names)  #rename coefficients
  }bv
```

From `texreg.rd`:
```
The \code{omit.coef} argument is processed after the \code{custom.coef.names} 
argument, so the regular expression should refer to the custom coefficient names.
```
Would it be helpful to have a pull request that flipped the order of the `omitcoef`and `customnames` functions for the three `*reg()` functions?

**Comment by czucca** [comment]
I replicated your code in the first message and 

```
texreg(reg, custom.coef.names=c('a', 'b3', 'b5'),
       omit.coef='2')  ## this omits "b5"
```

it does not omit b5, but it reports an error that says that three names have been attributed to two arguments. This is because the coefficient was omitted before the renaming. Hence, when it gets to rename there are two coefficients and not three any longer. 

In this other case

```
texreg(reg,  custom.coef.names=c('a', 'b3', 'b5'),
       omit.coef='b3')  ## output is unchanged 
```
the output is unchanged because `omit.coef` is processed before `custom.coef.names` and the variables do not have these names yet when they are processed by `omit.coef`, so it just cannot find the name b3.

Also, the part of the code you are quoting in the second message has been removed by the new update in September.

To make it work:
```
texreg(reg, custom.coef.names=c('a', 'b3', 'b5'),
       omit.coef='2')  ## this omits "b5"
```
this omits b5 because b5 is the second coefficient after the intercept, and it is correct, as explained in the documentation for `custom.coef.names`.

According to the documentation for `custom.coef.names`, if you want to remove the intercept you need to write
```
texreg(reg, custom.coef.names=c('a', 'b3', 'b5'),
       omit.coef='Intercept')  
```
otherwise the coefficient are called 1, 2 etc. after the Intercept. 

Hence, pass to `custom.coef.names` only the new names of the coefficients you want to keep and start the count of the other coefficients after the intercept.

Hope this helps, 

Best, 
C.
