### ISSUE TITLE
New texreg Version (1.36.24) not showing confidence intervals correctly.

### ISSUE THREAD

**Issue by czucca** [leifeld/texreg#89]
In the updated package 1.36.24 (not on CRAN) the function texreg does not show the confidence intervals correctly.
screenreg/htmlreg/matrixreg work correctly. 

example with texreg:
``
model <- lm(dist ~ speed, data=cars)
texreg(model, ci.force=T)``

```\begin{table}
\begin{center}
\begin{tabular}{l c }
\hline
 & Model 1 \\
\hline
(Intercept) &  $-17.58^{*}$                                                                 \\
            & $[-30.83;\ -4.33]$ [$[-30.83;\ -4.33]$; $[-30.83;\ -4.33]$]$[-30.83;\ -4.33]$ \\
speed       &    $3.93^{*}$                                                                 \\
            &   $[3.12;\ 4.75]$ [   $[3.12;\ 4.75]$;    $[3.12;\ 4.75]$]  $[3.12;\ 4.75]$   \\
\hline
R$^2$       &     0.65                                                                         \\
Adj. R$^2$  &     0.64                                                                      \\
Num. obs.   &    50                                                                         \\
RMSE        &    15.38                                                                      \\
\hline
\multicolumn{2}{l}{\scriptsize{$^*$ 0 outside the confidence interval.}}
\end{tabular}
\caption{Statistical models}
\label{table:coefficients}
\end{center}
\end{table}```



the correct output should be 
`\begin{table}
\begin{center}
\begin{tabular}{l c }
\hline
 & Model 1 \\
\hline
(Intercept) &  $-17.58^{*}$     \\
            & $[-30.83;\ -4.33]$   \\
speed       &    $3.93^{*}$        \\
            &   $[3.12;\ 4.75]$        \\
\hline
R$^2$       &     0.65                   \\
Adj. R$^2$  &     0.64                 \\
Num. obs.   &    50                     \\
RMSE        &    15.38                   \\
\hline
\multicolumn{2}{l}{\scriptsize{$^*$ 0 outside the confidence interval.}}
\end{tabular}
\caption{Statistical models}
\label{table:coefficients}
\end{center}
\end{table}
```
This is an example forcing CI, but the same problem shows in cases in which CIs are outomatically displayed

The problem might be (still checking, not entirely sure) on the last updated code (merged PR #44). Possibly the get_star function or in the way it interfaces with the texreg function.

**Comment by leifeld** [comment]
Thanks @czucca for finding this problem. It would be great if you could figure out a patch.

Including @vincentarelbundock for information.

**Comment by czucca** [comment]
I'm on it!

**Comment by vincentarelbundock** [comment]
I don't really understand why this new problem appeared. As far as I can tell, the confidence intervals get split up in a weird way by this loop (inside the `format.column` function):

https://github.com/leifeld/texreg/blob/master/R/internal.R#L895

I don't think I wrote that function, and I'm not exactly sure what it does. Perhaps the problem comes from the fact the call to `output.matrix` on line 89 introduces a weird double backslash inside the confidence interval brackets. The `format.column` regexes have an allergic reaction to that: 

https://github.com/leifeld/texreg/blob/master/R/texreg.R#L98

I'm not sure why those `\\` are inserted inside the confidence interval. Maybe the parentheses were escaped (as is often necessary), and a `gsub` call left unnecessarily escaped brackets in there. (This is very speculative). 

https://github.com/leifeld/texreg/blob/master/R/internal.R#L649

**Comment by vincentarelbundock** [comment]
@czucca I have a bunch of deadlines coming up, but ping me in a week if you don't find a solution; I should have more time to look into this then.

BTW, would be nice to include a couple `testthat` tests to ensure problems like this don't arise anymore. If you've never used that test package, check out my `countrycode` package for an example.

**Comment by czucca** [comment]
@vincentarelbundock, yes you are right, the problem is in the `format.column` function. The repetition of coefficients is produced here. 
https://github.com/leifeld/texreg/blob/master/R/internal.R#L911

The confidence intervals are inserted in place of the white spaces. 

Thanks for your suggestions and for the help offer! I'll keep you posted.
